/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AspiradorRouteImport } from './routes/aspirador'
import { Route as BobojacoRouteImport } from './routes/bobojaco'
import { Route as BodymodeladorRouteImport } from './routes/bodymodelador'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckoutSchutzRouteImport } from './routes/checkout-schutz'
import { Route as JaquetaRouteImport } from './routes/jaqueta'
import { Route as JaquetafemRouteImport } from './routes/jaquetafem'
import { Route as JeanswidelegRouteImport } from './routes/jeanswideleg'
import { Route as KitSandaliasRouteImport } from './routes/kit-sandalias'
import { Route as KitjeansRouteImport } from './routes/kitjeans'
import { Route as KitpanosRouteImport } from './routes/kitpanos'
import { Route as KitsandaliasRouteImport } from './routes/kitsandalias'
import { Route as MercadopromoRouteImport } from './routes/mercadopromo'
import { Route as Nb9060RouteImport } from './routes/nb-9060'
import { Route as OrtopedicaRouteImport } from './routes/ortopedica'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RoboaspiradorRouteImport } from './routes/roboaspirador'
import { Route as TranslucidaRouteImport } from './routes/translucida'
import { Route as Translucida2RouteImport } from './routes/translucida2'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicWebhooksHypercashRouteImport } from './routes/api/public/webhooks/hypercash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AspiradorRoute = AspiradorRouteImport.update({
  id: '/aspirador',
  path: '/aspirador',
  getParentRoute: () => rootRouteImport,
} as any)
const BobojacoRoute = BobojacoRouteImport.update({
  id: '/bobojaco',
  path: '/bobojaco',
  getParentRoute: () => rootRouteImport,
} as any)
const BodymodeladorRoute = BodymodeladorRouteImport.update({
  id: '/bodymodelador',
  path: '/bodymodelador',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSchutzRoute = CheckoutSchutzRouteImport.update({
  id: '/checkout-schutz',
  path: '/checkout-schutz',
  getParentRoute: () => rootRouteImport,
} as any)
const JaquetaRoute = JaquetaRouteImport.update({
  id: '/jaqueta',
  path: '/jaqueta',
  getParentRoute: () => rootRouteImport,
} as any)
const JaquetafemRoute = JaquetafemRouteImport.update({
  id: '/jaquetafem',
  path: '/jaquetafem',
  getParentRoute: () => rootRouteImport,
} as any)
const JeanswidelegRoute = JeanswidelegRouteImport.update({
  id: '/jeanswideleg',
  path: '/jeanswideleg',
  getParentRoute: () => rootRouteImport,
} as any)
const KitSandaliasRoute = KitSandaliasRouteImport.update({
  id: '/kit-sandalias',
  path: '/kit-sandalias',
  getParentRoute: () => rootRouteImport,
} as any)
const KitjeansRoute = KitjeansRouteImport.update({
  id: '/kitjeans',
  path: '/kitjeans',
  getParentRoute: () => rootRouteImport,
} as any)
const KitpanosRoute = KitpanosRouteImport.update({
  id: '/kitpanos',
  path: '/kitpanos',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsandaliasRoute = KitsandaliasRouteImport.update({
  id: '/kitsandalias',
  path: '/kitsandalias',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadopromoRoute = MercadopromoRouteImport.update({
  id: '/mercadopromo',
  path: '/mercadopromo',
  getParentRoute: () => rootRouteImport,
} as any)
const Nb9060Route = Nb9060RouteImport.update({
  id: '/nb-9060',
  path: '/nb-9060',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtopedicaRoute = OrtopedicaRouteImport.update({
  id: '/ortopedica',
  path: '/ortopedica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboaspiradorRoute = RoboaspiradorRouteImport.update({
  id: '/roboaspirador',
  path: '/roboaspirador',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslucidaRoute = TranslucidaRouteImport.update({
  id: '/translucida',
  path: '/translucida',
  getParentRoute: () => rootRouteImport,
} as any)
const Translucida2Route = Translucida2RouteImport.update({
  id: '/translucida2',
  path: '/translucida2',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksHypercashRoute =
  ApiPublicWebhooksHypercashRouteImport.update({
    id: '/api/public/webhooks/hypercash',
    path: '/api/public/webhooks/hypercash',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aspirador': typeof AspiradorRoute
  '/bobojaco': typeof BobojacoRoute
  '/bodymodelador': typeof BodymodeladorRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-schutz': typeof CheckoutSchutzRoute
  '/jaqueta': typeof JaquetaRoute
  '/jaquetafem': typeof JaquetafemRoute
  '/jeanswideleg': typeof JeanswidelegRoute
  '/kit-sandalias': typeof KitSandaliasRoute
  '/kitjeans': typeof KitjeansRoute
  '/kitpanos': typeof KitpanosRoute
  '/kitsandalias': typeof KitsandaliasRoute
  '/mercadopromo': typeof MercadopromoRoute
  '/nb-9060': typeof Nb9060Route
  '/ortopedica': typeof OrtopedicaRoute
  '/produtos': typeof ProdutosRoute
  '/roboaspirador': typeof RoboaspiradorRoute
  '/translucida': typeof TranslucidaRoute
  '/translucida2': typeof Translucida2Route
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aspirador': typeof AspiradorRoute
  '/bobojaco': typeof BobojacoRoute
  '/bodymodelador': typeof BodymodeladorRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-schutz': typeof CheckoutSchutzRoute
  '/jaqueta': typeof JaquetaRoute
  '/jaquetafem': typeof JaquetafemRoute
  '/jeanswideleg': typeof JeanswidelegRoute
  '/kit-sandalias': typeof KitSandaliasRoute
  '/kitjeans': typeof KitjeansRoute
  '/kitpanos': typeof KitpanosRoute
  '/kitsandalias': typeof KitsandaliasRoute
  '/mercadopromo': typeof MercadopromoRoute
  '/nb-9060': typeof Nb9060Route
  '/ortopedica': typeof OrtopedicaRoute
  '/produtos': typeof ProdutosRoute
  '/roboaspirador': typeof RoboaspiradorRoute
  '/translucida': typeof TranslucidaRoute
  '/translucida2': typeof Translucida2Route
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aspirador': typeof AspiradorRoute
  '/bobojaco': typeof BobojacoRoute
  '/bodymodelador': typeof BodymodeladorRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-schutz': typeof CheckoutSchutzRoute
  '/jaqueta': typeof JaquetaRoute
  '/jaquetafem': typeof JaquetafemRoute
  '/jeanswideleg': typeof JeanswidelegRoute
  '/kit-sandalias': typeof KitSandaliasRoute
  '/kitjeans': typeof KitjeansRoute
  '/kitpanos': typeof KitpanosRoute
  '/kitsandalias': typeof KitsandaliasRoute
  '/mercadopromo': typeof MercadopromoRoute
  '/nb-9060': typeof Nb9060Route
  '/ortopedica': typeof OrtopedicaRoute
  '/produtos': typeof ProdutosRoute
  '/roboaspirador': typeof RoboaspiradorRoute
  '/translucida': typeof TranslucidaRoute
  '/translucida2': typeof Translucida2Route
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aspirador'
    | '/bobojaco'
    | '/bodymodelador'
    | '/checkout'
    | '/checkout-schutz'
    | '/jaqueta'
    | '/jaquetafem'
    | '/jeanswideleg'
    | '/kit-sandalias'
    | '/kitjeans'
    | '/kitpanos'
    | '/kitsandalias'
    | '/mercadopromo'
    | '/nb-9060'
    | '/ortopedica'
    | '/produtos'
    | '/roboaspirador'
    | '/translucida'
    | '/translucida2'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aspirador'
    | '/bobojaco'
    | '/bodymodelador'
    | '/checkout'
    | '/checkout-schutz'
    | '/jaqueta'
    | '/jaquetafem'
    | '/jeanswideleg'
    | '/kit-sandalias'
    | '/kitjeans'
    | '/kitpanos'
    | '/kitsandalias'
    | '/mercadopromo'
    | '/nb-9060'
    | '/ortopedica'
    | '/produtos'
    | '/roboaspirador'
    | '/translucida'
    | '/translucida2'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aspirador'
    | '/bobojaco'
    | '/bodymodelador'
    | '/checkout'
    | '/checkout-schutz'
    | '/jaqueta'
    | '/jaquetafem'
    | '/jeanswideleg'
    | '/kit-sandalias'
    | '/kitjeans'
    | '/kitpanos'
    | '/kitsandalias'
    | '/mercadopromo'
    | '/nb-9060'
    | '/ortopedica'
    | '/produtos'
    | '/roboaspirador'
    | '/translucida'
    | '/translucida2'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AspiradorRoute: typeof AspiradorRoute
  BobojacoRoute: typeof BobojacoRoute
  BodymodeladorRoute: typeof BodymodeladorRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutSchutzRoute: typeof CheckoutSchutzRoute
  JaquetaRoute: typeof JaquetaRoute
  JaquetafemRoute: typeof JaquetafemRoute
  JeanswidelegRoute: typeof JeanswidelegRoute
  KitSandaliasRoute: typeof KitSandaliasRoute
  KitjeansRoute: typeof KitjeansRoute
  KitpanosRoute: typeof KitpanosRoute
  KitsandaliasRoute: typeof KitsandaliasRoute
  MercadopromoRoute: typeof MercadopromoRoute
  Nb9060Route: typeof Nb9060Route
  OrtopedicaRoute: typeof OrtopedicaRoute
  ProdutosRoute: typeof ProdutosRoute
  RoboaspiradorRoute: typeof RoboaspiradorRoute
  TranslucidaRoute: typeof TranslucidaRoute
  Translucida2Route: typeof Translucida2Route
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksHypercashRoute: typeof ApiPublicWebhooksHypercashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspirador': {
      id: '/aspirador'
      path: '/aspirador'
      fullPath: '/aspirador'
      preLoaderRoute: typeof AspiradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bobojaco': {
      id: '/bobojaco'
      path: '/bobojaco'
      fullPath: '/bobojaco'
      preLoaderRoute: typeof BobojacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodymodelador': {
      id: '/bodymodelador'
      path: '/bodymodelador'
      fullPath: '/bodymodelador'
      preLoaderRoute: typeof BodymodeladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-schutz': {
      id: '/checkout-schutz'
      path: '/checkout-schutz'
      fullPath: '/checkout-schutz'
      preLoaderRoute: typeof CheckoutSchutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaqueta': {
      id: '/jaqueta'
      path: '/jaqueta'
      fullPath: '/jaqueta'
      preLoaderRoute: typeof JaquetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaquetafem': {
      id: '/jaquetafem'
      path: '/jaquetafem'
      fullPath: '/jaquetafem'
      preLoaderRoute: typeof JaquetafemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeanswideleg': {
      id: '/jeanswideleg'
      path: '/jeanswideleg'
      fullPath: '/jeanswideleg'
      preLoaderRoute: typeof JeanswidelegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-sandalias': {
      id: '/kit-sandalias'
      path: '/kit-sandalias'
      fullPath: '/kit-sandalias'
      preLoaderRoute: typeof KitSandaliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitjeans': {
      id: '/kitjeans'
      path: '/kitjeans'
      fullPath: '/kitjeans'
      preLoaderRoute: typeof KitjeansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitpanos': {
      id: '/kitpanos'
      path: '/kitpanos'
      fullPath: '/kitpanos'
      preLoaderRoute: typeof KitpanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitsandalias': {
      id: '/kitsandalias'
      path: '/kitsandalias'
      fullPath: '/kitsandalias'
      preLoaderRoute: typeof KitsandaliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercadopromo': {
      id: '/mercadopromo'
      path: '/mercadopromo'
      fullPath: '/mercadopromo'
      preLoaderRoute: typeof MercadopromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nb-9060': {
      id: '/nb-9060'
      path: '/nb-9060'
      fullPath: '/nb-9060'
      preLoaderRoute: typeof Nb9060RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortopedica': {
      id: '/ortopedica'
      path: '/ortopedica'
      fullPath: '/ortopedica'
      preLoaderRoute: typeof OrtopedicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roboaspirador': {
      id: '/roboaspirador'
      path: '/roboaspirador'
      fullPath: '/roboaspirador'
      preLoaderRoute: typeof RoboaspiradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translucida': {
      id: '/translucida'
      path: '/translucida'
      fullPath: '/translucida'
      preLoaderRoute: typeof TranslucidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translucida2': {
      id: '/translucida2'
      path: '/translucida2'
      fullPath: '/translucida2'
      preLoaderRoute: typeof Translucida2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hypercash': {
      id: '/api/public/webhooks/hypercash'
      path: '/api/public/webhooks/hypercash'
      fullPath: '/api/public/webhooks/hypercash'
      preLoaderRoute: typeof ApiPublicWebhooksHypercashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AspiradorRoute: AspiradorRoute,
  BobojacoRoute: BobojacoRoute,
  BodymodeladorRoute: BodymodeladorRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutSchutzRoute: CheckoutSchutzRoute,
  JaquetaRoute: JaquetaRoute,
  JaquetafemRoute: JaquetafemRoute,
  JeanswidelegRoute: JeanswidelegRoute,
  KitSandaliasRoute: KitSandaliasRoute,
  KitjeansRoute: KitjeansRoute,
  KitpanosRoute: KitpanosRoute,
  KitsandaliasRoute: KitsandaliasRoute,
  MercadopromoRoute: MercadopromoRoute,
  Nb9060Route: Nb9060Route,
  OrtopedicaRoute: OrtopedicaRoute,
  ProdutosRoute: ProdutosRoute,
  RoboaspiradorRoute: RoboaspiradorRoute,
  TranslucidaRoute: TranslucidaRoute,
  Translucida2Route: Translucida2Route,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksHypercashRoute: ApiPublicWebhooksHypercashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
