/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ApiPublicWebhooksHypercashRouteImport } from './routes/api/public/webhooks/hypercash'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksHypercashRoute =
  ApiPublicWebhooksHypercashRouteImport.update({
    id: '/api/public/webhooks/hypercash',
    path: '/api/public/webhooks/hypercash',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/produtos': typeof ProdutosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/webhooks/hypercash': typeof ApiPublicWebhooksHypercashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/produtos'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/api/public/webhooks/hypercash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ProdutosRoute: typeof ProdutosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksHypercashRoute: typeof ApiPublicWebhooksHypercashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hypercash': {
      id: '/api/public/webhooks/hypercash'
      path: '/api/public/webhooks/hypercash'
      fullPath: '/api/public/webhooks/hypercash'
      preLoaderRoute: typeof ApiPublicWebhooksHypercashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ProdutosRoute: ProdutosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksHypercashRoute: ApiPublicWebhooksHypercashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
